---@alias Buffers [integer, integer]

--- Single cellular automaton's cell
---
---@class CellularAutomatonCell
---
--- Char representing one cell
--- NOTE: it always occupies one virtual column
---   but may consist of several bytes (maybe
---   composing characters as well)
---@field char string
---
--- Appropriate highlight group
--- for cell (or empty string)
---@field hl_group string

--- Two-dimensional grid representing
--- current cellular automaton's state
---
---@alias CellularAutomatonGrid CellularAutomatonCell[][]

--- Cellular automaton's (and animation's) common configuration
---
---@class CellularAutomatonConfig
---
--- Animation name
---@field name string
---
--- Frames per seconds for animation
---@field fps integer
---
--- (Optional) function for grid initialization
---@field init fun(CellularAutomatonGrid)?
---
--- Update function. Return true to notify that automaton
--- state has been changed and further processing needed
---@field update fun(CellularAutomatonGrid):boolean
